# Generated by Django 4.2.25 on 2025-10-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibliotheque", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livre",
            name="image",
        ),
        migrations.AddField(
            model_name="livre",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="livres_couvertures/"
            ),
        ),
        migrations.AlterField(
            model_name="livre",
            name="fichier",
            field=models.FileField(upload_to="fichiers/"),
        ),
    ]
