# Generated by Django 4.2.25 on 2025-10-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibliotheque", "0002_remove_livre_image_livre_cover_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorie",
            name="type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
