# Generated by Django 4.2.25 on 2025-10-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibliotheque", "0003_alter_categorie_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auteur",
            name="nom",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
