# Generated by Django 4.2.25 on 2025-10-21 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bibliotheque", "0004_alter_auteur_nom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livre",
            name="auteur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bibliotheque.auteur",
            ),
        ),
    ]
