# Generated by Django 4.2.25 on 2025-10-21 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bibliotheque", "0005_alter_livre_auteur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livre",
            name="auteur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bibliotheque.auteur",
            ),
        ),
    ]
