# Generated by Django 4.2.25 on 2025-10-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibliotheque", "0006_alter_livre_auteur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livre",
            name="datepublication",
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
