# Generated by Django 4.2.25 on 2025-10-25 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bibliotheque", "0008_livre_utilisateur"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livre",
            name="auteur",
        ),
    ]
