# Generated by Django 4.2.25 on 2025-10-26 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bibliotheque", "0009_remove_livre_auteur"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentaire",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reponses",
                to="bibliotheque.commentaire",
            ),
        ),
    ]
